repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
  - repo: https://github.com/hadolint/hadolint
    rev: v2.6.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/ashwin153/pre-commit-vagrant
    rev: v1.1.0
    hooks:
      - id: vagrant-validate
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
