apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  namespace: actions
spec:
  template:
    spec:
      repository: actions-runner-controller/actions-runner-controller
      image: wager/runtime
