apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
      scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
      scaleUpFactor: '1.4'        # The scale up multiplier factor applied to desired count
      scaleDownFactor: '0.7'
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
      - actions-runner-controller/actions-runner-controller
