name: cd
on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build .
      - name: Deploy to ghcr.io/wager/runtime
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker build --tag ghcr.io/wager/runtime .
          docker push ghcr.io/wager/runtime
      - name: Deploy to index.docker.io/wager/runtime
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build --tag wager/runtime .
          docker push wager/runtime
      - name: Detect Vulnerabilities
        uses: aquasecurity/trivy-action@0.0.18
        with:
          image-ref: wager/runtime
          ignore-unfixed: true
          # TODO: Add `exit-code: 1` once existing vulnerabilities are fixed.
