name: cd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ghcr.io/wager/runtime
        run: |
          echo ${{ secrets.GH_PACKAGES_PAT }} | docker login ghcr.io -u ashwin153 --password-stdin
          docker build . -t ghcr.io/wager/runtime
          docker push ghcr.io/wager/runtime
      - name: hub.docker.com/wager/runtime
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wager/runtime
