name: ci
on:
  pull_request:
  push:
    branches: 
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install Terraform
        run: sudo apt-get install terraform
      - name: Install Vagrant
        run: sudo apt-get install vagrant
      - name: Pre-Commit
        uses: pre-commit/action@v2.0.0
